create table if not exists public.room_readings (
  id bigint generated by default as identity primary key,
  room_id text not null,
  recorded_at timestamptz not null default now(),
  app_version text,
  sensor_online boolean not null default false,
  temperature_c numeric,
  humidity numeric,
  chip_temperature_c numeric,
  wifi_rssi integer,
  source text,
  uptime_ms bigint
);

alter table public.room_readings
add column if not exists chip_temperature_c numeric;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create index if not exists room_readings_room_time_idx
on public.room_readings (room_id, recorded_at desc);

alter table public.room_readings enable row level security;

create or replace function public.valid_room_device_token()
returns boolean
language sql
stable
set search_path = public, extensions
as $$
  select encode(extensions.digest(coalesce(
    nullif(current_setting('request.headers', true), '')::json ->> 'x-device-token',
    ''
  ), 'sha256'), 'hex') = '3e3d040c85243da01de6bee6ea1193fdee6c0c61cdd9e5ca34a886c490255f9f';
$$;

drop policy if exists room_readings_read on public.room_readings;
create policy room_readings_read
on public.room_readings
for select
to anon
using (room_id = 'main-room');

drop policy if exists room_readings_insert_device on public.room_readings;
create policy room_readings_insert_device
on public.room_readings
for insert
to anon
with check (room_id = 'main-room' and public.valid_room_device_token());

grant select, insert on public.room_readings to anon;
grant usage, select on sequence public.room_readings_id_seq to anon;

select pg_notify('pgrst', 'reload schema');
