-- LongOS semantic fixture captured from commit f589e75.
-- Execution order: room_latest.sql -> add_history.sql ->
-- snapshot_room_readings.sql -> enable_public_dashboard_read.sql.

create table if not exists public.room_latest (
  room_id text primary key,
  updated_at timestamptz not null default now(),
  app_version text,
  device_online boolean not null default false,
  wifi_connected boolean not null default false,
  wifi_mode text,
  wifi_rssi integer,
  free_heap integer,
  chip_temperature_c numeric,
  last_sensor_ok_ms bigint,
  temperature_c numeric,
  humidity numeric,
  sensor_online boolean not null default false,
  source text,
  uptime_ms bigint,
  local_ip text
);

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

alter table public.room_latest enable row level security;

create or replace function public.valid_room_device_token()
returns boolean
language sql
stable
set search_path = public, extensions
as $$
  select encode(extensions.digest(coalesce(
    nullif(current_setting('request.headers', true), '')::json ->> 'x-device-token',
    ''
  ), 'sha256'), 'hex') = '3e3d040c85243da01de6bee6ea1193fdee6c0c61cdd9e5ca34a886c490255f9f';
$$;

create or replace function public.set_room_latest_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_room_latest_updated_at on public.room_latest;
create trigger set_room_latest_updated_at
before insert or update on public.room_latest
for each row
execute function public.set_room_latest_updated_at();

drop policy if exists room_latest_read on public.room_latest;
create policy room_latest_read
on public.room_latest
for select
to anon
using (room_id = 'main-room');

drop policy if exists room_latest_insert_device on public.room_latest;
create policy room_latest_insert_device
on public.room_latest
for insert
to anon
with check (room_id = 'main-room' and public.valid_room_device_token());

drop policy if exists room_latest_update_device on public.room_latest;
create policy room_latest_update_device
on public.room_latest
for update
to anon
using (room_id = 'main-room' and public.valid_room_device_token())
with check (room_id = 'main-room' and public.valid_room_device_token());

grant select, insert, update on public.room_latest to anon;

insert into public.room_latest (
  room_id,
  app_version,
  device_online,
  wifi_connected,
  sensor_online,
  source
) values (
  'main-room',
  'waiting-for-esp32',
  false,
  false,
  false,
  'No data'
) on conflict (room_id) do nothing;

create table if not exists public.room_readings (
  id bigint generated by default as identity primary key,
  room_id text not null,
  recorded_at timestamptz not null default now(),
  app_version text,
  sensor_online boolean not null default false,
  temperature_c numeric,
  humidity numeric,
  chip_temperature_c numeric,
  wifi_rssi integer,
  source text,
  uptime_ms bigint
);

alter table public.room_readings
add column if not exists chip_temperature_c numeric;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create index if not exists room_readings_room_time_idx
on public.room_readings (room_id, recorded_at desc);

alter table public.room_readings enable row level security;

create or replace function public.valid_room_device_token()
returns boolean
language sql
stable
set search_path = public, extensions
as $$
  select encode(extensions.digest(coalesce(
    nullif(current_setting('request.headers', true), '')::json ->> 'x-device-token',
    ''
  ), 'sha256'), 'hex') = '3e3d040c85243da01de6bee6ea1193fdee6c0c61cdd9e5ca34a886c490255f9f';
$$;

drop policy if exists room_readings_read on public.room_readings;
create policy room_readings_read
on public.room_readings
for select
to anon
using (room_id = 'main-room');

drop policy if exists room_readings_insert_device on public.room_readings;
create policy room_readings_insert_device
on public.room_readings
for insert
to anon
with check (room_id = 'main-room' and public.valid_room_device_token());

grant select, insert on public.room_readings to anon;
grant usage, select on sequence public.room_readings_id_seq to anon;

select pg_notify('pgrst', 'reload schema');

create extension if not exists pg_cron;

create or replace function public.snapshot_room_reading()
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.room_readings (
    room_id,
    recorded_at,
    app_version,
    sensor_online,
    temperature_c,
    humidity,
    chip_temperature_c,
    wifi_rssi,
    source,
    uptime_ms
  )
  select
    latest.room_id,
    now(),
    latest.app_version,
    latest.sensor_online,
    latest.temperature_c,
    latest.humidity,
    latest.chip_temperature_c,
    latest.wifi_rssi,
    coalesce(latest.source, 'room_latest snapshot'),
    latest.uptime_ms
  from public.room_latest latest
  where latest.room_id = 'main-room'
    and latest.sensor_online = true
    and latest.temperature_c is not null
    and latest.humidity is not null
    and latest.updated_at > now() - interval '90 seconds'
    and not exists (
      select 1
      from public.room_readings existing
      where existing.room_id = latest.room_id
        and existing.sensor_online = true
        and existing.recorded_at > now() - interval '150 seconds'
    );
$$;

select cron.unschedule('autohome-snapshot')
where exists (
  select 1 from cron.job where jobname = 'autohome-snapshot'
);

select cron.schedule(
  'autohome-snapshot',
  '*/5 * * * *',
  $$ select public.snapshot_room_reading(); $$
);

select cron.unschedule('autohome-cleanup')
where exists (
  select 1 from cron.job where jobname = 'autohome-cleanup'
);

select cron.schedule(
  'autohome-cleanup',
  '17 3 * * *',
  $$ delete from public.room_readings where recorded_at < now() - interval '90 days'; $$
);

select public.snapshot_room_reading();

alter table public.room_latest enable row level security;
alter table public.room_readings enable row level security;

drop policy if exists room_latest_read on public.room_latest;
create policy room_latest_read
on public.room_latest
for select
to anon
using (room_id = 'main-room');

drop policy if exists room_readings_read on public.room_readings;
create policy room_readings_read
on public.room_readings
for select
to anon
using (room_id = 'main-room');

grant select on public.room_latest to anon;
grant select on public.room_readings to anon;

drop function if exists public.valid_room_dashboard_token();

select pg_notify('pgrst', 'reload schema');
