import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { gzipSync } from 'node:zlib';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const firmwarePath = resolve(root, 'src/main.cpp');
const outputPath = resolve(root, 'include/web_assets.h');

const assetDefinitions = [
  { name: 'INDEX_HTML_GZ', path: 'web/index.html', gzip: true },
  { name: 'FAVICON_SVG_GZ', path: 'web/favicon.svg', gzip: true },
  { name: 'APPLE_TOUCH_ICON_PNG', path: 'web/apple-touch-icon.png', gzip: false }
];

function formatByteArray(bytes) {
  const lines = [];
  for (let offset = 0; offset < bytes.length; offset += 16) {
    const values = [...bytes.subarray(offset, offset + 16)]
      .map((value) => `0x${value.toString(16).padStart(2, '0')}`)
      .join(', ');
    lines.push(`  ${values}`);
  }
  return lines.join(',\n');
}

function deterministicGzip(source) {
  const bytes = gzipSync(source, { level: 9, mtime: 0 });
  // zlib writes the host OS into byte 9; normalize it for cross-platform output.
  bytes[9] = 0xFF;
  return bytes;
}

const assets = await Promise.all(assetDefinitions.map(async (definition) => {
  const source = await readFile(resolve(root, definition.path));
  const bytes = definition.gzip
    ? deterministicGzip(source)
    : source;
  return { ...definition, sourceLength: source.length, bytes };
}));

const generatedBlocks = assets.map((asset) => {
  const encoding = asset.gzip ? 'gzip' : 'raw';
  return `// ${asset.path}: ${asset.sourceLength} bytes -> ${asset.bytes.length} bytes (${encoding})
static const uint8_t ${asset.name}[] PROGMEM = {
${formatByteArray(asset.bytes)}
};
static constexpr size_t ${asset.name}_LENGTH = sizeof(${asset.name});`;
});

const header = `#pragma once

#include <Arduino.h>

// Generated by tools/embed-web.mjs. Do not edit manually.
${generatedBlocks.join('\n\n')}
`;

await writeFile(outputPath, header);

// Remove the legacy raw HTML block when upgrading an existing checkout.
const firmware = await readFile(firmwarePath, 'utf8');
const legacyIndexHtmlBlock = /\nconst char INDEX_HTML\[\] PROGMEM = R"HTML\([\s\S]*?\)HTML";\n/;
const nextFirmware = firmware.replace(legacyIndexHtmlBlock, '\n');
if (nextFirmware !== firmware) {
  await writeFile(firmwarePath, nextFirmware);
}

for (const asset of assets) {
  console.log(`${asset.path}: ${asset.sourceLength} -> ${asset.bytes.length} bytes${asset.gzip ? ' (gzip)' : ''}`);
}
console.log('Generated include/web_assets.h.');
